#!/bin/bash

# Получаем директорию, где находится этот скрипт
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Запускаем Python-скрипт с переданными аргументами
python3 "$SCRIPT_DIR/main.py" "$@"
